[package]
name = "hello-actix-web"
version = "0.1.0"
edition = "2021"
authors = ["paoqi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
