[package]
name = "hello-rs"
version = "0.1.0"
edition = "2021"
authors = ["paoqi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://crates.io/crates/rand
rand = "0.8.4"
